### ISSUE TITLE
chisubmit arguments outdates or unclear

### ISSUE THREAD

**Issue by mtn** [uchicago-cs/cmsc23310#1]
When making a submission to chisubmit, I found that the directions didn't seem completely right. Specifically, when I tried to run a command formatted as

```
chisubmit student assignment submit <cnet-or-team> <assignment-id> <commit-sha>
```

per the directions on the site, I encountered a usage error

```
Usage: chisubmit student assignment submit [OPTIONS] ASSIGNMENT_ID

Error: Got unexpected extra arguments (p1a e9fd735482f4143c5f6e8b13eaad45d564a1715b)
```

The command that accepted my submission didn't include either of the last two parameters and automatically used the last commit hash for the only registered project. Maybe `OPTIONS` have to be passed in with some flags?

**Comment by borjasotomayor** [comment]
Where did you see those directions? The ones you cite are outdated and haven't been used in a while. The official documentation has the correct syntax for running the submission command:

http://chi.cs.uchicago.edu/chisubmit/students.html#making-the-submission

If you are following some other documentation, please post a link to it so we can look into it.

**Comment by mtn** [comment]
They are posted [on the current class site](https://uchicago-cs.github.io/cmsc23310/chisubmit.html#making-the-submissionl), rendered from this repository I think.

**Comment by borjasotomayor** [comment]
Please alert the instructor of that class about this (you may want to suggest that they simply link to the official chisubmit documentation). I am closing this issue because this is not an issue with chisubmit (nothing in the chisubmit repo or in the official documentation is wrong).

**Comment by borjasotomayor** [comment]
(sorry, I'm on my phone I just realized that this issue was posted on the cmsc23310 repo, not on the chisubmit repo, from which I get most of my notifications regarding chisubmit; I'm reopening this issue, but I suggest you bring this up directly with the instructor for the class instead of via a GitHub issue)

**Comment by mtn** [comment]
Will do, thank you!

**Comment by mtn** [comment]
Resolved.
